name: JumpAndRunLobby
version: 26.1.2
main: de.drpacket.jumpplugin.JumpPlugin
api-version: '1.21'
author: DrPacket
commands:
  jump:
    description: Startet die Jump-and-Run-Lobby-Arena
    usage: /jump
    aliases: [jr, jrun]
